services:
  gamer-challenges-db:
    image: postgres:17
    container_name: gamer-challenges-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - gc-network

  gamer-challenges-api:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: gamer-challenges-api
    restart: unless-stopped
    ports:
      - "${PORT}:5006"
    environment:
      - PORT=5006
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - NODE_ENV=${NODE_ENV}
      - PGHOST=gamer-challenges-db
      - PGPORT=${PG_PORT}
      - PGUSER=${PG_USER}
      - PGPASSWORD=${PG_PASSWORD}
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@gamer-challenges-db:${PG_PORT}/${PG_DATABASE}
    depends_on:
      - gamer-challenges-db
    networks:
      - gc-network

networks:
  gc-network:
