-- Generated by Mocodo 4.3.2

CREATE TABLE challenge (
  PRIMARY KEY (code_challenge),
  code_challenge   VARCHAR(42) NOT NULL,
  nom              VARCHAR(42),
  description      VARCHAR(42),
  regles           VARCHAR(42),
  date_creation    VARCHAR(42),
  code_jeu         VARCHAR(42) NOT NULL,
  code_utilisateur VARCHAR(42) NOT NULL
);

CREATE TABLE jeton (
  PRIMARY KEY (code_jeton),
  code_jeton       VARCHAR(42) NOT NULL,
  valeur           VARCHAR(42),
  type             VARCHAR(42),
  date_creation    VARCHAR(42),
  date_expiration  VARCHAR(42),
  code_utilisateur VARCHAR(42) NOT NULL
);

CREATE TABLE jeu (
  PRIMARY KEY (code_jeu),
  code_jeu  VARCHAR(42) NOT NULL,
  titre     VARCHAR(42),
  image_url VARCHAR(42)
);

CREATE TABLE participation (
  PRIMARY KEY (code_participation),
  code_participation VARCHAR(42) NOT NULL,
  titre              VARCHAR(42),
  video_url          VARCHAR(42),
  date_creation      VARCHAR(42),
  code_challenge     VARCHAR(42) NOT NULL,
  code_utilisateur   VARCHAR(42) NOT NULL
);

CREATE TABLE utilisateur (
  PRIMARY KEY (code_utilisateur),
  code_utilisateur VARCHAR(42) NOT NULL,
  pseudo           VARCHAR(42),
  avatar_url       VARCHAR(42),
  email            VARCHAR(42),
  mot_de_passe     VARCHAR(42),
  role             VARCHAR(42)
);

CREATE TABLE voter_challenge (
  PRIMARY KEY (code_utilisateur, code_challenge),
  code_utilisateur VARCHAR(42) NOT NULL,
  code_challenge   VARCHAR(42) NOT NULL
);

CREATE TABLE voter_participation (
  PRIMARY KEY (code_utilisateur, code_participation),
  code_utilisateur   VARCHAR(42) NOT NULL,
  code_participation VARCHAR(42) NOT NULL
);

ALTER TABLE challenge ADD FOREIGN KEY (code_utilisateur) REFERENCES utilisateur (code_utilisateur);
ALTER TABLE challenge ADD FOREIGN KEY (code_jeu) REFERENCES jeu (code_jeu);

ALTER TABLE jeton ADD FOREIGN KEY (code_utilisateur) REFERENCES utilisateur (code_utilisateur);

ALTER TABLE participation ADD FOREIGN KEY (code_utilisateur) REFERENCES utilisateur (code_utilisateur);
ALTER TABLE participation ADD FOREIGN KEY (code_challenge) REFERENCES challenge (code_challenge);

ALTER TABLE voter_challenge ADD FOREIGN KEY (code_challenge) REFERENCES challenge (code_challenge);
ALTER TABLE voter_challenge ADD FOREIGN KEY (code_utilisateur) REFERENCES utilisateur (code_utilisateur);

ALTER TABLE voter_participation ADD FOREIGN KEY (code_participation) REFERENCES participation (code_participation);
ALTER TABLE voter_participation ADD FOREIGN KEY (code_utilisateur) REFERENCES utilisateur (code_utilisateur);
