name: Run integration tests on API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_api_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Tear down previous Docker containers
        run: |
          npm run docker:test:down
          sleep 3

      - name: Run docker services
        run: npm run docker:test:up

      - name: Generate Prisma Client
        run: npm run db:test:generate

      - name: Run tests
        run: npm run test:spec
